### ISSUE TITLE
Issue with space in filepath

### ISSUE THREAD

**Issue by rhit-bowerirn** [sellersindustry/SherpaJS#61]
**Describe the bug**
The template project does not build when there is a space in the filepath

**To Reproduce**
1. Clone the template repo into a folder that has a space in the name: https://github.com/sellersindustry/SherpaJS-template-server
2. Run `npm install` and `npm run dev`

**Expected behavior**
The project was expected to build

**Additional context**
Supposedly "The issue is basically because there is a space in the file location and it's "%20" not a space"

**Comment by SellersEvan** [comment]
There is also an issue with paths being in different formats within the manifest. Update the `Files` modules and unsure that also file system utilization and linked using the `Files` utility. This will require adding additional methods like listing files in a do. Additionally verify all file paths are in UNIX format.

**Comment by SellersEvan** [comment]
[Drop-in Path Replacment](https://www.npmjs.com/package/@mojojs/path)
